
#ifndef _INAC_ERR_H_
#define _INAC_ERR_H_

enum {
	INAC_E_OK = 0,
	INAC_E_NO_DEV,
	INAC_E_OPEN_FAILED,
	INAC_E_READ_FAILED,
	INAC_E_MMAP_FAILED,
	INAC_E_IOCTL_FAILED,
	INAC_E_INVALID_BLOCK,
	INAC_E_INVALID_FORMAT,
	INAC_E_INVALID_CONFIG,	
	INAC_E_INVALID_STREAM,
	INAC_E_NO_MEM,
	INAC_E_NO_TX_BUFF,
	INAC_E_RULE_EXIST,
	INAC_E_RULE_NOT_EXIST,
	INAC_E_RULE_ID_EXIST,
	INAC_E_RULE_FULL,	
	INAC_E_IOCTL_UNDEFINED,
	INAC_E_INVALID_PARA,
	INAC_E_EXEC_FAILED,
	INAC_E_FAILED,
	INAC_E_INTERNAL_ERROR,
	INAC_E_MAX
};

#endif /* _INAC_ERR_H_ */

